apiVersion: apps/v1
kind: Deployment
metadata:
  name: team7-auth-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app: auth-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
      enableServiceLinks: false
      containers:
        - name: auth-server
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.images.authServer.repository }}:{{ .Values.images.authServer.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: auth-server-config
            - secretRef:
                name: {{ .Values.secrets.authServer }}
            - secretRef:
                name: {{ .Values.secrets.appConnections }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.services.authServer.port }}"
            - name: MANAGEMENT_SERVER_PORT
              value: "{{ .Values.services.authServer.port }}"
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
