apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: team7-ingestion-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: ingestion-api
    app.kubernetes.io/name: ingestion-api
    app.kubernetes.io/instance: team7-ingestion-api
spec:
  selector:
    matchLabels:
      app: ingestion-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
