crds:
  create: false

rbac:
  create: true
  namespaces:
    - skala3-finalproj-class2-team7

controller:
  type: daemonset

alloy:
  configMap:
    create: true
    content: |
      loki.write "default" {
        endpoint {
          url = "http://loki-gateway.skala3-finalproj-class2-team7.svc.cluster.local/loki/api/v1/push"
        }
      }

      discovery.kubernetes "pods" {
        role = "pod"

        namespaces {
          names = ["skala3-finalproj-class2-team7"]
        }
      }

      discovery.relabel "pods" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          target_label  = "app"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_instance"]
          target_label  = "instance"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_node_name"]
          target_label  = "node"
        }
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.relabel.pods.output
        forward_to = [loki.write.default.receiver]
      }
