apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: skala3-finalproj-class2-team7
spec:
  project: default

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.8.1
      helm:
        releaseName: alloy
        valueFiles:
          - $values/observability/logging/alloy-values.yaml

    - repoURL: https://github.com/skala-final-project-team7/infra.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: skala3-finalproj-class2-team7

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
