apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: skala3-finalproj-class2-team7
spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 85.0.3
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/observability/monitoring/values.yaml

    - repoURL: https://github.com/skala-final-project-team7/infra.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/skala-final-project-team7/infra.git
      targetRevision: main
      path: observability/monitoring/dashboards

    - repoURL: https://github.com/skala-final-project-team7/infra.git
      targetRevision: main
      path: observability/monitoring/rules

  destination:
    server: https://kubernetes.default.svc
    namespace: skala3-finalproj-class2-team7

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
