crds:
  enabled: false

global:
  rbac:
    create: false

kube-state-metrics:
  enabled: false
  rbac:
    create: false

prometheusOperator:
  admissionWebhooks:
    enabled: false
  rbac:
    create: false

grafana:
  enabled: true
  rbac:
    create: true
    namespaced: true

  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password

  service:
    type: ClusterIP

  ingress:
    enabled: false
    ingressClassName: nginx
    hosts:
      - grafana.team7.local
    path: /

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.skala3-finalproj-class2-team7.svc.cluster.local
      isDefault: false

prometheus:
  rbac:
    create: false
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

prometheus-node-exporter:
  enabled: false
